Ridderrasmus/RPVoiceChat

- mods/rpvoicechat/rpvoicechat.csproj
- mods/rpvoicechat/src/Audio/AudioOutputManager.cs
- mods/rpvoicechat/src/Audio/MicrophoneManager.cs
- mods/rpvoicechat/src/Networking/RPVoiceChatNativeNetwork.cs
- mods/rpvoicechat/src/Networking/RPVoiceChatNativeNetworkClient.cs
- mods/rpvoicechat/src/Networking/RPVoiceChatNativeNetworkServer.cs
- mods/rpvoicechat/src/Networking/RPVoiceChatSocketClient.cs
- mods/rpvoicechat/src/Networking/RPVoiceChatSocketServer.cs
- mods/rpvoicechat/src/RPVoiceChatClient.cs
- mods/rpvoicechat/src/RPVoiceChatMod.cs
- mods/rpvoicechat/src/RPVoiceChatServer.cs
- mods/rpvoicechat/src/Utils/AudioPacket.cs
- mods/rpvoicechat/src/Utils/PlayerAudioSource.cs
> Network fix

- src/Audio/AudioOutputManager.cs
- src/RPVoiceChatClient.cs
- src/Utils/PlayerAudioSource.cs
Adds few null checks here and there 
No longer will attempt to handle received audio packets or manage player sources if client hasn't fully connected to the server
> Fixes for exceptions caught on the stress test

- modinfo.json
- src/Audio/AudioOutputManager.cs
- src/Audio/CircularAudioBufer.cs
- src/Audio/Codecs/OpusCodec.cs
- src/Audio/MicrophoneManager.cs
- src/Audio/OpenALWrapper.cs
- src/Audio/PlayerAudioSource.cs
Fixes clicky noise in encoded audio
Fixes a flood of fake AL errors in the logs
Disables light silence denoising for a better user experience
Enriches audio capture related logging
Bumps version to 1.3.4
> Stress test fixes

- assets/rpvoicechat/config/recipedictionary.json
- assets/rpvoicechat/recipes/smithing/royalhornhandle.json
- src/Block/BlockRegistry.cs
- src/Config/RPVoiceChatConfig.cs
- src/Item/ItemRegistry.cs
- src/Networking/UDPNetwork/UDPNetworkBase.cs
- src/RPVoiceChatClient.cs
- src/RPVoiceChatServer.cs
- src/Utils/RecipeHandler.cs
Adds a config setting to disable modded content
Disables grid recipes and functionality of modded items/blocks if such setting is set
Fix exception thrown when disconnecting from a server
> Recipe toggle

- App.config
- RPVoiceChat.csproj
- modinfo.json
- src/Server/GameServer.cs
Ships `OpenTK.Mathematics` with the mod if client doesn't have it for whatever reason
Adds error handling during handshake
Bumps patch version
> Net7 hotfix

- README.md
- modinfo.json
- src/Audio/Input/MicrophoneManager.cs
- src/Audio/Output/AudioOutputManager.cs
- src/Audio/Output/PlayerAudioSource.cs
- src/Client/PlayerNetworkClient.cs
- src/Networking/UDPNetwork/UDPNetworkBase.cs
- src/RPVoiceChatClient.cs
- src/Server/GameServer.cs
- src/Utils/NetworkUtils.cs
Fixes #71
Fixes #72
Fixes #70
Adds a description of `AdditionalContent` config setting to README
Changes log message for failed server startup caused by UPnP to let people know that this is intentional behavior
Bumps patch version
> Fixes for multiple known issues 

- README.md
- assets/rpvoicechat/recipes/smithing/royalhornhandle.json
- src/Audio/Effects/EffectTemplate.cs
- src/Audio/Input/OpenALAudioCapture.cs
- src/Audio/Output/AudioOutputManager.cs
- src/Audio/Output/PlayerAudioSource.cs
- src/Block/BlockRegistry.cs
- src/Client/PlayerNetworkClient.cs
- src/Config/RPVoiceChatConfig.cs
- src/Item/ItemRegistry.cs
- src/Networking/UDPNetwork/UDPNetworkBase.cs
- src/RPVoiceChatClient.cs
- src/RPVoiceChatServer.cs
- src/Server/GameServer.cs
- src/Utils/NetworkUtils.cs
- src/Utils/RecipeHandler.cs
Merges features and fixes from .net7 branch into develop. 
**Already contains changes from #73.**
Adds a config setting to disable modded content
Disables grid recipes and functionality of modded items/blocks if such setting is set
Adds error handling during handshake
Fixes #71
Fixes #72
Fixes #70
Adds a description of AdditionalContent config setting to README
Changes log message for failed server startup caused by UPnP to let people know that this is intentional behavior
> Recent fixes

- src/Audio/Output/AudioOutputManager.cs
- src/Audio/Output/CircularAudioBufer.cs
- src/Audio/Output/PlayerAudioSource.cs
- src/Gui/PlayerNameTagRenderer.cs
- src/Patches/EntityNameTagRendererRegistry.cs
- src/Patches/PatchManager.cs
- src/RPVoiceChatClient.cs
Makes nametag of talking player flash green and display regardless of if player is hovered over or not
> Add indication of who is talking

- README.md
- assets/rpvoicechat/lang/en.json
- src/Audio/Input/MicrophoneManager.cs
- src/Config/RPVoiceChatConfig.cs
- src/Gui/CustomElements/AudioMeter.cs
- src/Gui/ModMenuDialog.cs
- src/Networking/UDPNetwork/UDPNetworkServer.cs
Adds advanced settings tab
Adds setting to toggle detection of audio channels
Adds setting to adjust max input threshold
Increases input gain limit to 200% with a warning not to do so
Increases output gain limit to 300%
Fixes incorrect volume adjustment during channel merge
Additional logging
> Extend mod settings

- src/Audio/Input/MicrophoneManager.cs
- src/Audio/Output/CircularAudioBufer.cs
- src/Client/PlayerNetworkClient.cs
- src/Config/ClientSettings.cs
- src/Config/ModConfig.cs
- src/Config/WorldConfig.cs
- src/Networking/INetworkServer.cs
- src/Networking/NativeNetwork/NativeNetworkClient.cs
- src/Networking/NativeNetwork/NativeNetworkServer.cs
- src/Networking/Packets/ConnectionInfo.cs
- src/Networking/Packets/NetworkPacket.cs
- src/Networking/UDPNetwork/UDPNetworkBase.cs
- src/Networking/UDPNetwork/UDPNetworkClient.cs
- src/Networking/UDPNetwork/UDPNetworkServer.cs
- src/RPVoiceChatClient.cs
- src/RPVoiceChatMod.cs
- src/RPVoiceChatServer.cs
- src/Server/GameServer.cs
- src/Utils/NetworkUtils.cs
- Fixes audio not being transmitted when main thread freezes
- Fixes possible audio buffer corruption caused by race conditions
- Fixes rare crash on exit caused by race condition in disposal of configs and server processing messages
- Fixes leftover audio in audio capture buffer(e.g. muting while talking, waiting few seconds and unmuting will play end of phrase captured when you initially pressed mute) 
- Fixes log message when client fails to connect with any transport supported by server
- Optimizes audio buffer cleanup
- Deduplicates code
- Removes unused/pointless code
- Code style improvements
> Refactor some old code to improve mod stability under heavy load

- src/Audio/AudioData.cs
- src/Audio/Codecs/IAudioCodec.cs
- src/Audio/Codecs/OpusCodec.cs
- src/Audio/Input/MicrophoneManager.cs
- src/Audio/Output/AudioOutputManager.cs
- src/Audio/Output/PlayerAudioSource.cs
- src/Networking/Packets/AudioPacket.cs
- src/RPVoiceChatServer.cs
- src/Utils/Logger.cs
Adapts commits made no net7 branch since #103 to 1.18.6
Adds command to toggle audio encoding
> Downstream commits from net7

- README.md
- modinfo.json
- src/Audio/Input/OpenALAudioCapture.cs
- src/Audio/Output/PlayerAudioSource.cs
- src/Client/PlayerNetworkClient.cs
- src/Config/RPVoiceChatConfig.cs
- src/Networking/IExtendedNetworkServer.cs
- src/Networking/INetworkServer.cs
- src/Networking/NativeNetwork/NativeNetworkBase.cs
- src/Networking/NativeNetwork/NativeNetworkClient.cs
- src/Networking/NativeNetwork/NativeNetworkServer.cs
- src/Networking/NativeNetwork/ServerSystemNetworkProcess.cs
- src/Networking/TCPNetwork/TCPConnection.cs
- src/Networking/UDPNetwork/UDPNetworkBase.cs
- src/Patches/NetworkAPI.cs
- src/Patches/PatchManager.cs
- src/Patches/SystemNetworkProcess.cs
- src/Patches/TcpNetServer.cs
- src/RPVoiceChatClient.cs
- src/RPVoiceChatMod.cs
- src/RPVoiceChatServer.cs
- src/Server/GameServer.cs
- src/Utils/AudioUtils.cs
**This PR includes commits from #112, make sure to merge it before this PR**
Makes UDP fault tolerant
Fixes a bug when default audio input device was always used if `MultiQuad` format is unavailable
Makes the mod attempt to create `Stereo` capture device before `Mono` to cover more channels
> Minor bug fixes 

- RPVoiceChat.csproj
- src/DB/ClientSettingsRepository.cs
- src/DB/DataRepository.cs
- src/DB/SQLiteDB.cs
- src/Gui/ModMenuDialog.cs
Brings the 1.19 compatibility changes onto the main development branch
> 1.19 compatibility

- assets/rpvoicechat/blocktypes/callbell.json
- assets/rpvoicechat/blocktypes/claymold/smallbellpartsmold.json
- assets/rpvoicechat/itemtypes/handbell.json
- assets/rpvoicechat/itemtypes/royalhorn.json
- assets/rpvoicechat/itemtypes/smallbellparts.json
- assets/rpvoicechat/lang/en.json
- assets/rpvoicechat/lang/fr.json
* Add new entries for Handbook
* Small fixes on smallbellparts mold
> Handbook entries

- modinfo.json
- src/BlockBehaviors/BehaviorRingable.cs
> Ringable crash fix

- src/Patches/TcpNetServer.cs
> Fiw TcpNetwork message queue using same classes as VC Core

- src/Networking/NativeNetwork/ServerSystemNetworkProcess.cs
> Added instance of FrameProfilerUtil for server network thread

- modinfo.json
- src/Blocks/BlockRegistry.cs
- src/Items/ItemRegistry.cs
- src/Networking/NativeNetwork/ServerSystemNetworkProcess.cs
- src/RPVoiceChatServer.cs
* Prevent future issues with "FromSocketListener" soon decomissioned by Vintage Story Dev Team
* "AdditionnalContent" conf now deactivated extra blocks (already deactivate extra items)
> Remove "FromSocketListener" usage

- RPVoiceChat.csproj
- assets/rpvoicechat/blocktypes/carillonbell.json
- modinfo.json
* Update Concetus to 1.1.7 to 2.2.2
* Fix non-spammable carillon bell
* Update VS version needed to 1.21.0-rc.1
> Concentus update

- src/BlockBehaviors/BehaviorRingable.cs
- src/BlockEntityBehaviors/BEBehaviorRingable.cs
> Fix a client crash when a door with a bell is open
